version: '3'

services:
  quarkus-app:
    image: labseqbackend:latest
    ports:
      - "8080:8080"
    networks:
      - labseq-network

  angular-app:
    image: labseqfrontend:latest
    ports:
      - "4200:80"
    networks:
      - labseq-network
    depends_on:      
      - quarkus-app
      
networks:
  labseq-network:
    driver: bridge
