version: '3'

services:
  labseqfrontend:
    image: labseqfrontend
    container_name: labseqfrontend
    ports:
      - "4200:4200"
    depends_on:
      - labseqbackend
    networks:
      - labseq_network

  labseqbackend:
    image: labseqbackend
    container_name: labseqbackend
    ports:
      - "8080:8080"
    networks:
      - labseq_network

networks:
  labseq_network:
    driver: bridge

